### ISSUE TITLE
How to use camel-jamod as dispatcher

### ISSUE THREAD

**Issue by imranrazakhan** [sworisbreathing/camel-jamod#6]
I am not expert of modbus but i have requirement to listen modbus tcp and dispatch that request two modbus masters based on slaveid, Can we achieve this? As both masters are deployed on one system so they are listening on ports 1502 and 2502, but client can only send request on 502 so i want to listen on 502 and send back on base of slaveid.

How i can achieve this?

**Comment by sworisbreathing** [comment]
Hi @imranrazakhan, sorry for the incredibly late reply. Unfortunately I've been well away from doing work with camel or modbus for the better part of the last decade so I'm not really sure how to do what you're trying to achieve. Hope you can figure something out.

In the meantime I'm going through a bunch of cleanup of my GitHub repositories - deleting anything I've forked that I'm no longer working on, and archiving the ones that I'm no longer working on which aren't forked (including camel-jamod).

All the best,
